excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://Amuwa.github.io
title: Optimization Science
tagline: Optimization, Science
description: To Optimize in a Scientific Style
paginate: 5
