#!/bin/bash
git add *.html
git add *.yml
git add *.md
git add gitpush
git add _includes/* 
git add _layouts/*
git add _posts/*
git add public/*
git commit -m "update posts"
git push origin master




